name: client
description: A Flutter project.
publish_to: 'none' # prevents the package from being accidentally published to pub.dev
version: 1.0.0+1 # defines the version and build number for your application
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 # adds the Cupertino Icons font to your application.
  graphql_flutter: ^4.0.1 
  path:  # define the locations within directory structure
  qr_flutter: ^4.0.0 # generates images of QR code
  qr_code_scanner: # decode string of QR code
  sqflite: # interact with a SQLite database
  awesome_notifications: any # generate a local notification
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
